markdown_ext: "md"

baseurl: "https://neic.no"

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      path: "news"
      type: "pages"
    values:
      layout: master
      include: generic
      permalink: /:path/:basename.html
  -
    scope:
      type: "pages"
    values:
      layout: master
      include: generic
      permalink: /:path/:basename/
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: master
      include: post
      permalink: /news/:year/:month/:day/:title/

collections:
  activities:
    output: true
    permalink: /:collection/:path/
  people:
    output: true
    permalink: /:collection/:path/
  alumni:
    output: true
    permalink: /:collection/:path/
